[Interface]
PrivateKey = MPcpPj12AZCfB65qCEdruIVtH6aIBfF1fE2uwN8BqlI=
Address = 10.66.66.11/32, fd42:42:42::11/128
DNS = 1.1.1.1, 1.0.0.1

[Peer]
PublicKey = sW5TZYovaeWZSlDOtOLfZA7VEvgLcGd8+Kt5WfsNswk=
PresharedKey = wh57p7kzvVrb9DJnmjdNVDenzlZwUUsduVZZCNhASqg=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 178.208.89.88:52979